# server属性配置
server:
  port: 8888

# Spring属性配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.102.43.224:3306/jz_zzqg?characterEncoding=utf8
    username: root
    password: liang..100398

# 日志配置
logging:
  file:
    path: d:/data/logs
    name: d:/data/logs/mylog.log
  level:
    com.zzuli.housekeepingserver.dao: debug
#  config: classpath:config/logback-spring.xml

# Mybatis属性配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true  # 开启驼峰命名
  mapper-locations: classpath:/mapper/**/*.xml

# swagger配置
knife4j:
  basic:
    username: admin
    password: 12345
    enable: true  # 开启认证
  production: false # 默认是false ,屏蔽所有Swagger的相关资源
  enable: true # 是否开启swagger
